# Generated by Django 5.1.4 on 2025-03-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_newpost_delete_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='post_id',
        ),
    ]
