# Generated by Django 5.1.4 on 2025-03-03 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_remove_newpost_post_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frinds', models.JSONField(default=list)),
                ('frind_requests_done', models.JSONField(default=list)),
                ('frind_requests_received', models.JSONField(default=list)),
                ('following', models.JSONField(default=list)),
                ('follow_request_done', models.JSONField(default=list)),
                ('follow_requests_received', models.JSONField(default=list)),
                ('followed_by', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('recommended_by', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
