# Generated by Django 5.1.4 on 2025-03-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_userdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='frind_requests_done',
            new_name='friend_requests_done',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='frind_requests_received',
            new_name='friend_requests_received',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='frinds',
            new_name='friends',
        ),
    ]
