# Generated by Django 5.1.4 on 2025-03-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_rename_frind_requests_done_userdetails_friend_requests_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='comments',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='newpost',
            name='liked_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='newpost',
            name='recommended_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='newpost',
            name='shared_by',
            field=models.JSONField(default=list),
        ),
    ]
