# Generated by Django 5.1.4 on 2025-03-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0006_newpost_comments_newpost_liked_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.CharField(default='', max_length=255),
        ),
    ]
