# Generated by Django 5.1.4 on 2025-03-04 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_userdetails_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newPost',
            new_name='Posts',
        ),
    ]
