# Generated by Django 5.1.7 on 2025-03-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0008_rename_newpost_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
