# Generated by Django 5.1.4 on 2025-03-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0010_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='room_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
