# Generated by Django 5.1.4 on 2025-03-18 20:28

import demo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0011_chatroom_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=demo_app.models.user_directory_path),
        ),
    ]
