# Generated by Django 5.1.4 on 2025-03-19 16:44

import demo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0012_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_picture',
            field=models.ImageField(default='default/defaultprofpic.jpg', upload_to=demo_app.models.user_directory_path),
        ),
    ]
