# Generated by Django 5.1.4 on 2025-03-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0013_alter_userdetails_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='likes',
            field=models.JSONField(default=list),
        ),
    ]
